PD-205376 - Added utility method to get bv container elements from open shadow dom.
bazaarvoice/bv-ui-core pull request #131
Opened 2023-04-19 05:46 UTC by shrinathnayak07

2023-04-19 10:08 UTC, akshay-choulwar-94 commented on lib/queryShadowDom/index.js
> +function shadowQuerySelectorAll (element, matchSelector) {
We need to cover the use case what if element or matchSelector is undefined

2023-04-19 10:10 UTC, akshay-choulwar-94 requested changes
Added few minor comments. Also can we try to write the unit tests for this code.

2023-04-21 07:23 UTC, akshay-choulwar-94 approved these changes
Looks good to me.

2023-05-02 11:19 UTC, Shubhakar-A approved these changes
Looks good to me

2023-05-05 05:52 UTC, soumen-saniel requested changes

2023-05-05 05:52 UTC, soumen-saniel commented on lib/queryShadowDom/README.md
> +| `matchSelector` | `string` | **Required**. Criteria to select the elements in the dom starting with element as root element. |
In all of the functions 1st param is a dom node.
Its better to use consistent naming `element` or `node` in all of the functions.

2023-05-05 05:52 UTC, soumen-saniel commented on lib/queryShadowDom/index.js
> +/**
In this file as well have the param names consistent for dom element
Name it `element` or `node`

2023-05-05 05:52 UTC, soumen-saniel commented on lib/queryShadowDom/index.js
> +  if (node.shadowRoot) {
Better to have a null check in place `node?.shadowRoot` or `node && node.shadowRoot`

2023-05-08 06:12 UTC, soumen-saniel approved these changes
Looks good

2023-05-15 05:51 UTC, soumen-saniel approved these changes
Looks good

2023-05-15 09:57 UTC, merged