fix: added boolean return for global set to fix Proxy set trapped error
bazaarvoice/bv-ui-core pull request #134
Opened 2023-08-11 12:36 UTC by Shubhakar-A

# PR description

## JIRA tickets

[PD-215136](https://bazaarvoice.atlassian.net/browse/PD-215136)

## This PR is for

- Bug

## Requirements / issues

- BV loader throws ''set' on proxy: trap returned falsish for property javascript' error when latest global of bv-ui-core
- This is because, BV namespace has its own proxy and a setter which tries to set properties to window.BV
- global do not return any boolean in its setter method - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy/set#return_value

## Solutions

- Add boolean return for global's return method

## Unit tests

- N/A

## Version

- Patch - 2.8.2

[PD-215136]: https://bazaarvoice.atlassian.net/browse/PD-215136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-08-11 14:23 UTC, soumen-saniel requested changes

2023-08-14 04:02 UTC, soumen-saniel requested changes

2023-08-14 04:02 UTC, soumen-saniel commented on lib/global/index.js
> +        return true
This should be just
```
set: function (target, prop, value, receiver) {
  return Reflect.set(target, prop, value, receiver)
},
```

2023-08-17 08:49 UTC, soumen-saniel approved these changes
Looks good

2023-08-17 08:51 UTC, anishbvoice approved these changes
Looks good

2023-08-17 09:30 UTC, merged