Bv fetch module
bazaarvoice/bv-ui-core pull request #136
Opened 2024-03-20 03:55 UTC by VarshaAdigaBV

[PD-230727](https://bazaarvoice.atlassian.net/browse/PD-230727)

## Problem/Goal

Creating bvFetch module. whose purpose is to cache duplicate api calls. 

## Solution

Created the module which caches the api responses based on the url. 

[PD-230727]: https://bazaarvoice.atlassian.net/browse/PD-230727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-03-20 09:34 UTC, RahulSubramaniam17 requested changes

2024-03-20 09:34 UTC, RahulSubramaniam17 commented on lib/bvFetch/index.js
> +        return window.fetch(url).then(response => {
Can we use the fetch polyfill instead of this as some clients may have overridden the window.fetch

2024-03-20 09:34 UTC, RahulSubramaniam17 commented on lib/bvFetch/index.js
> +                  console.log('Data cached');
we can remove console.log

2024-03-20 09:34 UTC, RahulSubramaniam17 commented on lib/bvFetch/index.js
> +          }).catch(err => {
Why are we adding so many catch blocks. I think one catch block will do the same

2024-03-22 09:28 UTC, RahulSubramaniam17 approved these changes
Looks good to me

2024-03-22 09:31 UTC, RahulSubramaniam17 approved these changes

2024-03-25 06:02 UTC, soumen-saniel approved these changes
Reviewed and approved

2024-03-25 06:10 UTC, RahulSubramaniam17 approved these changes

2024-03-25 06:15 UTC, merged